### PR TITLE
truncate and format large numbers

### LINKED ISSUE #1429: "Unlock Voting" can't display all decimals
**Bug Description**
Tried to self delegate. Had dust of UNI from adding liquidity. Dialogue couldn't handle the dust

**Steps to Reproduce**

1. Go to "Vote"
2. Click on "Unlock Voting"
3. Self Delegate

image

**Expected Behavior**
All decimals fit in.

### LINKED ISSUE #1434: Truncate token balances in cases where there is dust
Let's truncate to six sig figs. I.e.

`.00000000001123 ETH` should become `< .000001 ETH`

Screen Shot 2021-05-04 at 6 28 21 PM

### PR DESCRIPTION
**Pull request by ianlapham**
- fixes #1429 
- fixes #1434

### CODE REVIEW

File: src/utils/formatTokenAmount.ts [hunk 1]
```diff
@@ -10,11 +10,11 @@ export function formatTokenAmount(amount: CurrencyAmount<Currency> | undefined,
     return '0'
   }
 
-  if (parseFloat(amount.toFixed(Math.min(sigFigs, amount.currency.decimals))) < 0.0001) {
-    return '<0.0001'
+  if (parseFloat(amount.toSignificant(Math.min(sigFigs, amount.currency.decimals))) < 0.000001) {
```
Comment (moodysalem) [inline src/utils/formatTokenAmount.ts:13]: probably cleaner to do something like `amount.divide(amount.decimalScale).lessThan(new Fraction(1, 100000))`
