### PR TITLE
fix: display pool shares < 10%

### LINKED ISSUE #1612: UI displaying wrong share of liquidity pool
**Bug Description**
UI displaying wrong share of liquidity pool
**Steps to Reproduce**

Add more than 1% liquidity to an existing pool, ui will say <0.01%

**Expected Behavior**
UI correctly shows the share

**Additional Context**
 https://gyazo.com/2812f22a490c4f092ef67b07c668e1a3 https://gyazo.com/dfef30fb7bfac1adb080c61b590e2194

### PR DESCRIPTION
**Pull request by justindomingue**
fix #1612

### CODE REVIEW

File: src/constants/misc.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export const BIG_INT_SECONDS_IN_WEEK = JSBI.BigInt(60 * 60 * 24 * 7)
 export const BIG_INT_ZERO = JSBI.BigInt(0)
 
 // one basis JSBI.BigInt
-export const ONE_BIPS = new Percent(JSBI.BigInt(1), JSBI.BigInt(10))
+export const ONE_BIPS = new Percent(JSBI.BigInt(1), JSBI.BigInt(100))
```
Comment (moodysalem) [inline src/constants/misc.ts:17]: 1 bips is 1/10_000
