### PR TITLE
improvement(swap): progress bar and more minimal default UI, also fix custom add/remove

### LINKED ISSUE #801: Change approve button UX
All UI states with an approve button should be presented like the Sign & Confirm UI to help users understand there are two steps to complete. 

Screen Shot 2020-05-19 at 10 41 35 AM

Confirm & Sign UI for reference:
Screen Shot 2020-05-19 at 10 39 57 AM

### PR DESCRIPTION
**Pull request by ianlapham**
closes #801 
- add progress bars to swap to make it more clear that its a 2 step process if approval is needed
- change approve button to a green confirmed button when complete
- make default swap UI more dynamic - only show price and 'estimated' if trade details are populated 
- also fixes token adding and removal by updating check for custom added tokens
- approval states: 
Screen Shot 2020-08-26 at 2 24 20 PM
Screen Shot 2020-08-26 at 2 15 03 PM

### CODE REVIEW

File: src/components/Button/index.tsx [hunk 1]
```diff
@@ -253,11 +253,15 @@ const ButtonErrorStyle = styled(Base)`
...
+export function ButtonConfirmed({
+  confirmed,
+  altDisbaledStyle,
+  ...rest
+}: { confirmed?: boolean; altDisbaledStyle?: boolean } & ButtonProps) {
   if (confirmed) {
     return <ButtonConfirmedStyle {...rest} />
   } else {
-    return <ButtonPrimary {...rest} />
+    return <ButtonPrimary {...rest} altDisbaledStyle={altDisbaledStyle} />
```
Comment (moodysalem) [inline src/components/Button/index.tsx:264]: typo

Comment (moodysalem) [reply src/components/Button/index.tsx:264]: also don't think this is doing anything

File: src/pages/Swap/index.tsx [hunk 2]
```diff
@@ -294,7 +295,9 @@ export default function Swap() {
 
           <AutoColumn gap={'md'}>
             <CurrencyInputPanel
-              label={independentField === Field.OUTPUT && !showWrap ? 'From (estimated)' : 'From'}
+              label={
+                independentField === Field.OUTPUT && !showWrap && trade?.executionPrice ? 'From (estimated)' : 'From'
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:299]: trade?.executionPrice seems to be a proxy for trade

File: src/pages/Swap/index.tsx [hunk 3]
```diff
@@ -327,7 +329,7 @@ export default function Swap() {
             <CurrencyInputPanel
               value={formattedAmounts[Field.OUTPUT]}
               onUserInput={handleTypeOutput}
-              label={independentField === Field.INPUT && !showWrap ? 'To (estimated)' : 'To'}
+              label={independentField === Field.INPUT && !showWrap && trade?.executionPrice ? 'To (estimated)' : 'To'}
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:332]: same here

File: src/pages/Swap/index.tsx [hunk 4]
```diff
@@ -352,19 +354,20 @@ export default function Swap() {
...
-                    <TradePrice
-                      inputCurrency={currencies[Field.INPUT]}
-                      outputCurrency={currencies[Field.OUTPUT]}
-                      price={trade?.executionPrice}
-                      showInverted={showInverted}
-                      setShowInverted={setShowInverted}
-                    />
-                  </RowBetween>
-
+                  {trade?.executionPrice && (
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:357]: and here. why didn't we just use Boolean(trade)?

File: src/pages/Swap/index.tsx [hunk 5]
```diff
@@ -352,19 +354,20 @@ export default function Swap() {
...
+                    <RowBetween align="center">
+                      <Text fontWeight={500} fontSize={14} color={theme.text2}>
+                        Price
+                      </Text>
+                      <TradePrice
+                        inputCurrency={currencies[Field.INPUT]}
+                        outputCurrency={currencies[Field.OUTPUT]}
+                        price={trade?.executionPrice}
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:365]: no more ? needed

File: src/pages/Swap/index.tsx [hunk 6]
```diff
@@ -352,19 +354,20 @@ export default function Swap() {
...
-                    />
-                  </RowBetween>
-
+                  {trade?.executionPrice && (
+                    <RowBetween align="center">
+                      <Text fontWeight={500} fontSize={14} color={theme.text2}>
+                        Price
+                      </Text>
+                      <TradePrice
+                        inputCurrency={currencies[Field.INPUT]}
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:363]: i think the price already has the base/quote currency so might as well reduce this component to just take the price

File: src/components/Button/index.tsx (hunk 1 above)
Comment (ianlapham) [reply src/components/Button/index.tsx:264]: fixed the typo everywhere - we just need that to keep it a solid color background but also have it be in the disabled state (not clickable), the regular disabled state has the grey background

File: src/components/swap/TradePrice.tsx [hunk 7]
```diff
@@ -8,27 +8,19 @@ import { StyledBalanceMaxMini } from './styleds'
...
-  setShowInverted
-}: TradePriceProps) {
+export default function TradePrice({ price, showInverted, setShowInverted }: TradePriceProps) {
   const theme = useContext(ThemeContext)
 
   const formattedPrice = showInverted ? price?.toSignificant(6) : price?.invert()?.toSignificant(6)
 
-  const show = Boolean(inputCurrency && outputCurrency)
+  const show = Boolean(price?.baseCurrency && price?.quoteCurrency)
   const label = showInverted
```
Comment (moodysalem) [inline src/components/swap/TradePrice.tsx:21]: You could even let the parent component do the price inverting instead of taking `showInverted`, and rename `setShowInverted` to `onInvertPrice`

File: src/pages/Swap/index.tsx (hunk 5 above)
Comment (moodysalem) [reply src/pages/Swap/index.tsx:362]: still see a `?`, not a big deal though

File: src/pages/Swap/index.tsx [hunk 8]
```diff
@@ -463,6 +466,7 @@ export default function Swap() {
                 </Text>
               </ButtonError>
             )}
+            {showApproveFlow && <ProgresSteps steps={[approval === ApprovalState.APPROVED]} />}
```
Comment (moodysalem) [inline src/pages/Swap/index.tsx:469]: typo in progress, also only one step?

Comment (ianlapham) [reply src/pages/Swap/index.tsx:469]: One step because on swap completion it resets - i just made the component handle arbitrary amount of steps, so could use it in the future for multistep
