### PR TITLE
fix(L2): update downtime warning copy

### LINKED ISSUE #2047: Update schedule downtime text
On the Add Liquidity page, please update the downtime text to the following

Title:  "Optimism Schedule Downtime" (singular not plural)

Description:  "Optimism expects scheduled downtime in the near future. Unplanned downtime can occur unexpectedly. While the network is down, fees will not be generated and you will be unable to remove liquidity even while L1 market price moves. Read more."

'Read more' should link to this help article:  https://help.uniswap.org/en/articles/5406082-what-happens-if-the-optimistic-ethereum-network-experiences-downtime

### PR DESCRIPTION
**Pull request by JFrankfurt**
resolves #2047

### CODE REVIEW

File: src/components/OptimismDowntimeWarning/index.tsx [hunk 1]
```diff
@@ -44,18 +45,15 @@ export default function OptimismDowntimeWarning() {
     <Root>
       <TitleRow>
         <WarningIcon />
-        <Trans>{'Optimism'} Scheduled Downtimes</Trans>
+        <Trans>{'Optimism'} Scheduled Downtime</Trans>
```
Comment (justindomingue) [inline src/components/OptimismDowntimeWarning/index.tsx:48]: FYI `{'Optimism'}` didn't actually extract into a variable in the extraction step. :/

**Review by justindomingue — APPROVED** [review]

**Review by willhennessy — COMMENTED** [review]
sorry I just learned the hard lesson that Github review comments require an additional 'submit' click... if it weren't for the missing 'space' I would happily let this go but think we should fix that typo :)
