### PR TITLE
fix: division by 0 error when both reserves are 0

### LINKED ISSUE #1583: Crash report: `RangeError: Division by zero`
v2 version of #1582 (running on localhost, ae27e24)

## URL
  
http://localhost:3000/#/add/v2/ETH/0x1Faa0c671B6336527efD167F7d1C6Fc1b8A05D1a

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
RangeError: Division by zero
```

## Stacktrace

```
RangeError: Division by zero
    at Function.value (http://localhost:3000/static/js/vendors~main.chunk.js:74070:35)
    at CurrencyAmount.get (http://localhost:3000/static/js/vendors~main.chunk.js:33776:58)
    at new CurrencyAmount (http://localhost:3000/static/js/vendors~main.chunk.js:33803:72)
    at Function.fromFractionalAmount (http://localhost:3000/static/js/vendors~main.chunk.js:33827:12)
    at CurrencyAmount.divide (http://localhost:3000/static/js/vendors~main.chunk.js:33866:27)
    at Pair.get (http://localhost:3000/static/js/vendors~main.chunk.js:35148:41)
    at Pair.priceOf (http://localhost:3000/static/js/vendors~main.chunk.js:35028:64)
    at http://localhost:3000/static/js/main.chunk.js:58979:46
    at updateMemo (http://localhost:3000/static/js/vendors~main.chunk.js:128877:23)
    at Object.useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:129417:20)
    at useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:199356:25)
    at useDerivedMintInfo (http://localhost:3000/static/js/main.chunk.js:58965:70)
    at AddLiquidity (http://localhost:3000/static/js/main.chunk.js:42327:84)
    at renderWithHooks (http://localhost:3000/static/js/vendors~main.chunk.js:128018:22)
    at updateFunctionComponent (http://localhost:3000/static/js/vendors~main.chunk.js:130340:24)
    at beginWork (http://localhost:3000/static/js/vendors~main.chunk.js:131993:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:116968:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:117017:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:117077:35)
    at beginWork$1 (http://localhost:3000/static/js/vendors~main.chunk.js:136819:11)
    at performUnitOfWork (http://localhost:3000/static/js/vendors~main.chunk.js:135655:16)
    at workLoopSync (http://localhost:3000/static/js/vendors~main.chunk.js:135592:9)
    at renderRootSync (http://localhost:3000/static/js/vendors~main.chunk.js:135558:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:135175:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:124428:30
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:203808:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:124374:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:124423:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:124411:7)
    at batchedUpdates$1 (http://localhost:3000/static/js/vendors~main.chunk.js:135269:11)
    at Object.notify (http://localhost:3000/static/js/vendors~main.chunk.js:186243:7)
    at Subscription.notifyNestedSubs (http://localhost:3000/static/js/vendors~main.chunk.js:186314:20)
    at Subscription.handleChangeWrapper (http://localhost:3000/static/js/vendors~main.chunk.js:186319:12)
    at dispatch (http://localhost:3000/static/js/vendors~main.chunk.js:201210:7)
    at http://localhost:3000/static/js/vendors~main.chunk.js:200787:17
    at http://localhost:3000/static/js/vendors~main.chunk.js:30866:22
    at http://localhost:3000/static/js/vendors~main.chunk.js:30715:32
    at http://localhost:3000/static/js/main.chunk.js:61019:48
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

### PR DESCRIPTION
**Pull request by justindomingue**
fixes #1583

IUniswapV2Pair.getReserves() returns a 'valid' pair for some tokens (see #1583). However, the reserves are both set to 0 whhich leads to a division by zero down the line.

Fix suggested is to consider a pair where both reserves are 0 as NOT_EXISTS.

### CODE REVIEW

File: src/hooks/useV2Pairs.ts [hunk 1]
```diff
@@ -48,6 +48,7 @@ export function useV2Pairs(currencies: [Currency | undefined, Currency | undefin
       if (!tokenA || !tokenB || tokenA.equals(tokenB)) return [PairState.INVALID, null]
       if (!reserves) return [PairState.NOT_EXISTS, null]
       const { reserve0, reserve1 } = reserves
+      if (reserve0.isZero() && reserve1.isZero()) return [PairState.NOT_EXISTS, null]
```
Comment (moodysalem) [inline src/hooks/useV2Pairs.ts:51]: i wonder if this breaks adding liquidity to a v2 pair that exists but is not initialized

Comment (NoahZinsmeister) [reply src/hooks/useV2Pairs.ts:51]: yeah i was looking as well, it shouldn't because `addLiquidity` is isomorphic. however we should go through all the cases where `PairState.NOT_EXISTS` is used to drive logic to make sure this is ok. in particular i already found a bug in `AddLiquidityV2 > index.tsx`, the `isCreate` flag is no longer valid

Comment (justindomingue) [reply src/hooks/useV2Pairs.ts:51]: Should I just handle checking reserve0/1 = 0 in the caller to avoid changing the behavior everywhere?

**Review by moodysalem — APPROVED** [review]
